import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import {base,token,get} from '../api';
import {text} from '../text';
import {Heading,Select,useData,Row,Stage,Badges,Notice} from '../common';
const colors:any=['match',['get','stage'],'planned','#8b9698','being_built','#3984c6','in_use','#258665','needs_repair','#cb802b','under_repair','#8559a7','retired','#454c50','#258665'];
export function MapCanvas({filters='',shape,onPick}:{filters?:string,shape?:any,onPick?:(id:string)=>void}){const element=useRef<HTMLDivElement>(null);const pick=useRef(onPick);pick.current=onPick;useEffect(()=>{if(!element.current)return;const map=new maplibregl.Map({container:element.current,center:[72.65,23.22],zoom:12,style:{version:8,sources:{base:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'base',type:'raster',source:'base'}]},transformRequest:url=>url.startsWith(base)?{url,headers:{Authorization:'Bearer '+token()}}:{url}});map.addControl(new maplibregl.NavigationControl());map.on('load',()=>{if(shape){map.addSource('one',{type:'geojson',data:{type:'Feature',properties:{},geometry:shape}});map.addLayer({id:'one-fill',type:'fill',source:'one',filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':'#197967','fill-opacity':.35}});map.addLayer({id:'one-line',type:'line',source:'one',paint:{'line-color':'#197967','line-width':4}});map.addLayer({id:'one-point',type:'circle',source:'one',filter:['==',['geometry-type'],'Point'],paint:{'circle-color':'#197967','circle-radius':9}});const coordinates=shape.type==='Point'?[shape.coordinates]:shape.coordinates.flat(shape.type==='Polygon'?1:0);const bounds=new maplibregl.LngLatBounds();coordinates.forEach((p:any)=>bounds.extend(p));map.fitBounds(bounds,{padding:40,maxZoom:16});return;}
map.addSource('assets',{type:'vector',tiles:[base+'/map/{z}/{x}/{y}.pbf'+(filters?'?'+filters:'')],minzoom:0,maxzoom:18});
map.addLayer({id:'areas',type:'fill',source:'assets','source-layer':'assets',filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':colors,'fill-opacity':.35}});
map.addLayer({id:'lines',type:'line',source:'assets','source-layer':'assets',filter:['==',['geometry-type'],'LineString'],paint:{'line-color':colors,'line-width':4}});
map.addLayer({id:'points',type:'circle',source:'assets','source-layer':'assets',filter:['all',['==',['geometry-type'],'Point'],['!', ['has','count']]],paint:{'circle-color':colors,'circle-radius':6,'circle-stroke-width':2,'circle-stroke-color':'#fff'}});
map.addLayer({id:'groups',type:'circle',source:'assets','source-layer':'assets',filter:['has','count'],paint:{'circle-color':'#164b43','circle-radius':['interpolate',['linear'],['get','count'],1,12,100,24,10000,38],'circle-stroke-color':'#fff','circle-stroke-width':2}});
map.on('click',e=>{const features=map.queryRenderedFeatures(e.point,{layers:['points','lines','areas','groups']});const row=features[0];if(row?.properties?.id)pick.current?.(row.properties.id);else if(row?.properties?.count){new maplibregl.Popup().setLngLat(e.lngLat).setText(String(row.properties.count)+' '+text.assets.toLowerCase()).addTo(map);map.flyTo({center:e.lngLat,zoom:Math.max(10,map.getZoom()+2)})}});
});return()=>map.remove()},[filters,shape]);return <div className="map-canvas" ref={element}/>}
export default function MapPage(){const [filters,setFilters]=useState<Record<string,string>>({});const [chosen,setChosen]=useState<Row|null>(null);const [error,setError]=useState('');const [q,setQ]=useState('');const types=useData('/asset-types').data||[];const results=useData('/assets?q='+encodeURIComponent(q)).data||[];const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString();return <><Heading title={text.mapTitle} subtitle={text.mapHelp}/><section className="panel map-panel"><div className="filters"><Select label={text.type} value={filters.type_id||''} onChange={v=>setFilters({...filters,type_id:v})} items={types.map((t:Row)=>[String(t.id),t.name])}/><Select label={text.stage} value={filters.stage_key||''} onChange={v=>setFilters({...filters,stage_key:v})} items={Object.entries(text.stages)}/><label>{text.search}<input value={q} onChange={e=>setQ(e.target.value)}/></label></div>{q&&<div className="search-results">{results.slice(0,5).map((r:Row)=><button key={r.id} onClick={()=>get('/assets/'+r.id).then(setChosen)}>{r.register_code} · {r.name}</button>)}</div>}<Notice error={error}/><div className="map-layout"><MapCanvas filters={query} onPick={id=>get('/assets/'+id).then(setChosen).catch(e=>setError(e.message))}/>{chosen&&<aside className="map-card"><button className="quiet" onClick={()=>setChosen(null)}>{text.close}</button><p className="eyebrow">{chosen.register_code}</p><h2>{chosen.name||text.noName}</h2><p>{chosen.type.name} · {chosen.area}</p><Stage value={chosen.stage_key}/><Badges row={chosen}/><MapCanvas shape={chosen.shape}/><Link className="button primary" to={'/assets/'+chosen.id}>{text.open}</Link></aside>}</div><div className="legend">{Object.entries(text.stages).map(([key])=><Stage key={key} value={key}/>)}</div><small>{text.mapNote}</small></section></>}
