import {createContext,useContext,useEffect,useState,ReactNode} from 'react';
import {Link} from 'react-router-dom';
import {get} from './api';
import {text,label,Role} from './text';
export type Row=Record<string,any>;
export const Person=createContext<Row>({role:'viewer'});
export function usePerson(){return useContext(Person)}
export function useData(path:string){const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [version,setVersion]=useState(0);useEffect(()=>{let active=true;setData(null);setError('');get(path).then(value=>active&&setData(value)).catch(e=>active&&setError(e.message));return()=>{active=false}},[path,version]);return {data,error,reload:()=>setVersion(v=>v+1)};}
export function Notice({error}:{error?:string}){return error?<div role="alert" className="notice error">{error}</div>:null}
export function Heading({title,subtitle,children}:{title:string,subtitle?:string,children?:ReactNode}){return <header className="page-heading"><div><p className="eyebrow">{text.internal}</p><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{children}</header>}
export function Stage({value}:{value:string}){return <span className={'stage '+value}>{label(text.stages,value)}</span>}
export function Badges({row}:{row:Row}){return <div className="badges">{row.details?._sample&&<span>{text.sample}</span>}{row.repair_hold&&<span className="warn">{text.hold}</span>}{row.open_problem_count>0&&<span className="warn">{row.open_problem_count} {text.openProblems.toLowerCase()}</span>}{row.warranty_end&&new Date(row.warranty_end)>=new Date()&&<span>{text.warranty} · {row.warranty_end}</span>}{row.is_active===false&&<span>{text.inactive}</span>}</div>}
export function Empty(){return <p className="empty">{text.empty}</p>}
export function DataTable({rows,columns}:{rows:Row[],columns:[string,(row:Row)=>ReactNode][]}){return !rows.length?<Empty/>:<div className="table-wrap"><table><thead><tr>{columns.map(([name])=><th key={name}>{name}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id||i}>{columns.map(([name,render])=><td key={name}>{render(row)}</td>)}</tr>)}</tbody></table></div>}
export function AssetTable({rows}:{rows:Row[]}){return <DataTable rows={rows} columns={[[text.code,r=><Link to={'/assets/'+r.id}>{r.register_code}</Link>],[text.name,r=><><strong>{r.name||text.noName}</strong><Badges row={r}/></>],[text.type,r=>r.type],[text.area,r=>r.area],[text.stage,r=><Stage value={r.stage_key}/>]]}/>}
export function JsonView({value}:{value:unknown}){if(value==null)return <span>—</span>;if(typeof value!=='object')return <span>{String(value)}</span>;return <dl className="details">{Object.entries(value as Row).filter(([key])=>!['raw','geometry_wkt','asset_type_id','link_id','contract_id'].includes(key)).map(([key,item])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{typeof item==='object'?JSON.stringify(item):String(item??'—')}</dd></div>)}</dl>}
export function Select({label:caption,value,onChange,items,all=true}:{label:string,value:string,onChange:(v:string)=>void,items:[string,string][],all?:boolean}){return <label>{caption}<select value={value} onChange={e=>onChange(e.target.value)}>{all&&<option value="">{text.all}</option>}{items.map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label>}
export function Pager({page,setPage,count}:{page:number,setPage:(n:number)=>void,count:number}){return <div className="pager"><button disabled={page===1} onClick={()=>setPage(page-1)}>{text.previous}</button><span>{text.page} {page}</span><button disabled={count<50} onClick={()=>setPage(page+1)}>{text.next}</button></div>}
export function Action({run,children,after}:{run:()=>Promise<unknown>,children:ReactNode,after?:()=>void}){const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await run();after?.()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{children}</button><Notice error={error}/></>}
