import {describe,it,expect,vi} from 'vitest';
import {renderToString} from 'react-dom/server';
import {MemoryRouter} from 'react-router-dom';
import {Person} from './common';
import {canVisit,text,Role} from './text';
import SignIn from './pages/SignIn';
import AssetList from './pages/AssetList';
import AssetPage from './pages/AssetPage';
import MapPage from './pages/MapPage';
import BringInData from './pages/BringInData';
import ReviewQueue from './pages/ReviewQueue';
import ReviewItem from './pages/ReviewItem';
import Contracts from './pages/Contracts';
import Problems from './pages/Problems';
import Reports from './pages/Reports';
import Admin from './pages/Admin';
import HowItWorks from './pages/HowItWorks';
vi.mock('maplibre-gl',()=>({default:{}}));
describe('Page smoke checks',()=>{for(const Page of [SignIn,AssetList,AssetPage,MapPage,BringInData,ReviewQueue,ReviewItem,Contracts,Problems,Reports,Admin,HowItWorks])it(Page.name,()=>{expect(()=>renderToString(<MemoryRouter><Person.Provider value={{id:1,role:'admin'}}><Page/></Person.Provider></MemoryRouter>)).not.toThrow()})});
describe('Menu access',()=>{for(const role of Object.keys(text.roles) as Role[])it(role,()=>{expect(canVisit(role,'/assets')).toBe(true);expect(canVisit(role,'/admin')).toBe(role==='admin');expect(canVisit(role,'/imports')).toBe(['editor','admin'].includes(role))})});
it('has no blank screen words',()=>{function check(value:unknown){if(typeof value==='string')expect(value.trim().length).toBeGreaterThan(0);else if(value&&typeof value==='object')Object.values(value).forEach(check)}check(text)});
